name: shoesly
repository: https://github.com/Rk-Thakur/Shoesly.git

packages:
  - packages/*
scripts:
    analyze: 
        exec: dart analyze .

    format:
      description: Format Dart Code
      exec: dart format .

    clean:
      description: Clean all packages
      exec: flutter clean  