name: shoesly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shoesly_resources: any
  shoesly_core: any 
  shoesly_components: any
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  hive: ^2.2.3
  path_provider: ^2.1.3
  firebase_analytics: ^10.10.5
  firebase_auth: ^4.19.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.7.0
  injector: ^3.0.0
  dio: ^5.4.3+1
  font_awesome_flutter: ^10.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  cloud_firestore: ^4.17.3
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true




  assets:
    - assets/