name: shoesly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shoesly_resources: ^1.0.0
  shoesly_core: ^1.0.0
  shoesly_components: ^1.0.0
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true




