// File generated by "melos run svg". Do not edit by hand.
// Copyright (c) 2023. The Shoesly Authors. All rights reserved.

final class Asset {
  static const AssetImages images = AssetImages();
}

final class AssetImages {
  const AssetImages();

  String get xlingbold => 'assets/images-bin/xlingbold.svg.vec';
  String get jordonshafe => 'assets/images-bin/jordonshafe.svg.vec';
  String get addidasshade => 'assets/images-bin/addidasshade.svg.vec';
  String get vanshade => 'assets/images-bin/vanshade.svg.vec';
  String get book => 'assets/images-bin/book.svg.vec';
  String get pumashade => 'assets/images-bin/pumashade.svg.vec';
  String get nikeshade => 'assets/images-bin/nikeshade.svg.vec';
  String get onboard1 => 'assets/images-bin/onboard1.svg.vec';
  String get onboard2 => 'assets/images-bin/onboard2.svg.vec';
  String get onboard3 => 'assets/images-bin/onboard3.svg.vec';
  String get addidasbold => 'assets/images-bin/addidasbold.svg.vec';
  String get shoe2 => 'assets/images-bin/shoe2.svg.vec';
  String get pumabold => 'assets/images-bin/pumabold.svg.vec';
  String get xlingshade => 'assets/images-bin/xlingshade.svg.vec';
  String get shoe1 => 'assets/images-bin/shoe1.svg.vec';
  String get nikebold => 'assets/images-bin/nikebold.svg.vec';
}
