// File generated by "melos run svg". Do not edit by hand.
// Copyright (c) 2023. The LMS Authors. All rights reserved.

final class Asset {
  static const AssetImages images = AssetImages();
}

final class AssetImages {
  const AssetImages();

  String get book => 'assets/images-bin/book.svg.vec';
}
