name: shoesly_resources
description: Resources for the shoesly package
version: 1.0.0
publish_to: 'none'
environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.10.4'


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_graphics_compiler: ^1.1.11+1
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/images/
    - assets/images-bin/


