on:
  pull_request:
    branches:
      - "shoesly"

  push:
    branches:
      - "shoesly"

name: "Build and Release"
jobs:
  build:  
    name: Build and Release"  
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        project: [packages/shoesly]
      fail-fast: true

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:   
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Flutter pub get
        working-directory: ${{ matrix.project }}
        run: flutter pub get

      - name: Build APK
        if: matrix.project == 'packages/shoesly'
        working-directory: ${{ matrix.project }}
        run: flutter build apk  
      
      - name: Push to Release
        if: matrix.project == 'packages/shoesly'
        uses: ncipollo/release-action@v1
        with: 
          artifacts: "build/app/output/apk/debug/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
          